### ISSUE TITLE
** 변수 이름 통일하기

### ISSUE THREAD

**Issue by minkky** [minkky/SWE#13]
no -> cancel 로 통일해야함

**Comment by estanie** [comment]
큽... 알고보니 cancel이었습니다... 저희가 오타냈던것....ㅎㅅㅎ...

**Comment by estanie** [comment]
전 바보에여... cancle이 실제로 존재하는 단어인 줄 알았던 것...ㅠㅠ

**Comment by minkky** [comment]
앜ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ넼ㅋㅋ
나의 iPhone에서 보냄

2016. 12. 6. 오후 2:13 estanie <notifications@github.com> 작성:
